CREATE TABLE `Session` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , TOKEN VARCHAR(128) NOT NULL
    , USER_ID INT NOT NULL

    , PRIMARY KEY (TOKEN)
    , FOREIGN KEY (USER_ID)
            REFERENCES `User` (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);