CREATE TABLE `Project` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , TIMESTAMP_DELETED TIMESTAMP NULL
    , ID INT PRIMARY KEY AUTO_INCREMENT
    , NAME VARCHAR(100) NOT NULL
    , DATABASE_TYPE VARCHAR(50)
    , USER_ID_CREATED INT NOT NULL
    , USER_ID_DELETED INT NULL

    , FOREIGN KEY (USER_ID_CREATED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
    , FOREIGN KEY (USER_ID_DELETED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
);