CREATE TABLE `ProjectUser` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , PROJECT_ID INT NOT NULL
    , USER_ID INT NOT NULL
    , USER_ID_CREATED INT NOT NULL

    , PRIMARY KEY (PROJECT_ID, USER_ID)
    , FOREIGN KEY (PROJECT_ID)
            REFERENCES `Project` (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
    , FOREIGN KEY (USER_ID)
            REFERENCES `User` (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
    , FOREIGN KEY (USER_ID_CREATED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
            ON UPDATE CASCADE
);