CREATE TABLE `Script` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , TIMESTAMP_UPDATED TIMESTAMP NULL DEFAULT NULL
    , ID INT PRIMARY KEY AUTO_INCREMENT
    , PROJECT_ID INT NOT NULL
    , TITLE VARCHAR(300) NOT NULL
    , DESCRIPTION TEXT DEFAULT ''
    , USER_ID_CREATED INT NOT NULL
    , USER_ID_UPDATED INT NULL

    , FOREIGN KEY (PROJECT_ID)
            REFERENCES `Project` (ID)
            ON DELETE CASCADE
    , FOREIGN KEY (USER_ID_CREATED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
);