CREATE TABLE `ScriptTemplate` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , TIMESTAMP_UPDATED TIMESTAMP DEFAULT NULL
    , PROJECT_ID INT NOT NULL
    , SCRIPT_ID INT NULL
    , APPLY_TO_EACH_STATEMENT BOOLEAN NOT NULL DEFAULT FALSE
    , APPLY_AFTER BOOLEAN NOT NULL DEFAULT FALSE
    , QUERY TEXT
    , USER_ID_CREATED INT NOT NULL
    , USER_ID_UPDATED INT NULL

    , PRIMARY KEY (PROJECT_ID, SCRIPT_ID, APPLY_TO_EACH_STATEMENT, APPLY_AFTER)
    , FOREIGN KEY (PROJECT_ID)
            REFERENCES `Project` (ID)
            ON DELETE CASCADE
    , FOREIGN KEY (SCRIPT_ID)
            REFERENCES `Script` (ID)
            ON DELETE CASCADE
    , FOREIGN KEY (USER_ID_CREATED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
    , FOREIGN KEY (USER_ID_UPDATED)
            REFERENCES `User` (ID)
            ON DELETE RESTRICT
);