CREATE TABLE `User` (
    TIMESTAMP_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
    , TIMESTAMP_ARCHIVED TIMESTAMP NULL
    , ID INT PRIMARY KEY AUTO_INCREMENT
    , NAME VARCHAR(100) NOT NULL
    , USERNAME VARCHAR(100) DEFAULT NULL UNIQUE
    , EMAIL VARCHAR(500) DEFAULT NULL
    , ADMINISTRATOR BOOLEAN NOT NULL DEFAULT FALSE
    , PASSWORD_HASH VARCHAR(1024) DEFAULT NULL
);